### DISCUSSION TITLE
[GitLab反代] 非标准443端口上的GitLab实例，通过WAF反代，链接跳转会丢失端口

### DISCUSSION THREAD

**Discussion by mazhewei** [chaitin/SafeLine#1096] [Q&A]
GitLab的启动参数如下（docker-compose.yml）：
```yml
version: '3.8'
services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    container_name: gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://my-domain:10000'
        # 禁用letsencrypt
        letsencrypt['enable'] = false
        # 配置SSL证书(不用配置了，证书放到WAF中)
        # nginx['ssl_certificate'] = "/etc/gitlab/cert/my-domain.pem"
        # nginx['ssl_certificate_key'] = "/etc/gitlab/cert/my-domain.key"
        # 修改ssh端口
        gitlab_rails['gitlab_shell_ssh_port'] = 8888
        # 配置root初始密码，仅首次启动容器有效
        gitlab_rails['initial_root_password'] = "xxxxxxxx"
        # 禁用自带的https，https由WAF实现
        nginx['listen_https'] = false
        nginx['listen_port'] = 80
        # 配置时区
        gitlab_rails['time_zone'] = 'Asia/Shanghai'
        # 开启gitlab Pages功能
        # gitlab_pages['enable'] = true
        # 禁用远程头像
        gitlab_rails['gravatar_enabled'] = false
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '1000:80'
      - '8888:22'
    volumes:
      - '/home/gitlab/config:/etc/gitlab'
      - '/home/gitlab/cert:/etc/gitlab/cert'
      - '/home/gitlab/logs:/var/log/gitlab'
      - '/home/gitlab/data:/var/opt/gitlab'

networks:
    default:
        driver: "bridge"
```

除上面的设置外，其他设置使用GitLab默认，GitLab版本是[14.6.1](https://gitlab.com/gitlab-org/gitlab-foss/-/tags/v14.6.1)

然后WAF上的反向代理配置如下：
域名：my-domain
端口：10000
类型：代理一个已有的网站
证书：选择上传的证书
上游服务器：http://localhost:1000

保存提交后访问：https://my-domain:10000
访问不到，浏览器自动重定向会变成：https://my-domain 端口号丢失了
如果手工访问：https://my-domain:10000/users/sign_in 则可以打开登录界面

WAF站点全局设置：
SSL协议：TLSv1.2
为上游服务器传递 X-Forwarded-Host、 X-Forwarded-Proto：启用
支持 GZip 压缩：启用
支持 Brotli 压缩：启用

请问有没有办法能解决端口号丢失的问题？有人做过类似的场景吗？谢谢
