### ISSUE TITLE
是否可以部署到k8s？

### ISSUE THREAD

**Issue by charnet1019** [chaitin/SafeLine#118]

**Comment by DeronW** [comment]
商业版可以 https://waf-ce.chaitin.cn/

![image](https://github.com/chaitin/safeline/assets/780596/d8c6a901-4b4d-4ddc-8c21-46676d84b839)

**Comment by charnet1019** [comment]
@DeronW 后期是否有开放提供k8s部署的机会？如果已经开源了只需要限制功能就可以了，部署方式是不是就没必要再限制了

**Comment by zclaiqcc** [comment]
没有限制部署方式，只是说社区版直接部署到 K8s 上还不太方便。既然都开源了师傅当然可以随便 DIY，配置文件都在 compose.yaml 和各个容器里面，没有加任何限制。

**Comment by yrluke** [comment]
原理上讲是可以部署的，师傅可以试试

**Comment by charnet1019** [comment]
目前勉强成功部署到k8s上，目前有如下问题:
1. 因safeline-mgt-api中的nginx.conf中代理的postgresql的地址写死为safeline-postgres，需要手工修改对应的外置pg service name，如下所示
```yaml
upstream postgres {
        #server safeline-postgres:5432;
        server postgresql-hl.middleware:5432;
}
```
2. 目前waf代理的域名是通过在safeline-tengine中增加虚拟主机配置实现，所以需要将对应的监听端口允许外部访问，在deployment中设置hostNetwork为true时，添加域名后无法提交，如下所示:
 
![image](https://github.com/chaitin/safeline/assets/18616254/e49e980c-0300-45d2-a18c-74066e3db53f)

> 1. 建议完善下官方文档，说明下每个服务的监听端口、作用及其服务调用关系
> 2. 因问题1需要手动修改pg配置，所以是否只可以把相关服务的Dockerfile和二进制程序也放到一个仓库中，这样大家可以根据实际情况修改下Dockerfile的处理逻辑

## 服务部署编排如下:
- safeline-mgt-api.yaml
```yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mgr-api-certs
  namespace: waf
spec:
  storageClassName: nfs-based-cstor-storage
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Mi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mgr-api-nginx-conf
  namespace: waf
spec:
  storageClassName: nfs-based-cstor-storage
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Mi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mgr-api-logs
  namespace: waf
spec:
  storageClassName: nfs-based-cstor-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: safeline-mgt-api
    component: secure
  name: safeline-mgt-api
  namespace: waf
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: safeline-mgt-api
      component: secure
  template:
    metadata:
      labels:
        app: safeline-mgt-api
        component: secure
    spec:
      imagePullSecrets:
      - name: harborsecret
      volumes:
      - name: mgr-api-certs
        persistentVolumeClaim:
          claimName: mgr-api-certs
      - name: mgr-api-nginx-conf
        persistentVolumeClaim:
          claimName: mgr-api-nginx-conf
      - name: mgr-api-logs
        persistentVolumeClaim:
          claimName: mgr-api-logs
      containers:
      - name: safeline-mgt-api
        image: chaitin/safeline-mgt-api:2.0.1
        # image: 192.168.30.19/chaitin/safeline-mgt-api:2.0.0
        volumeMounts:
        - name: mgr-api-certs
          mountPath: /resources/management
        - name: mgr-api-nginx-conf
          mountPath: /resources/nginx
        - name: mgr-api-logs
          mountPath: /logs
        imagePullPolicy: Always
        env:
        - name: MANAGEMENT_RESOURCES_DIR
          value: /resources/management
        - name: NGINX_RESOURCES_DIR
          value: /resources/nginx
        - name: DATABASE_URL
          value: postgres://safeline-ce:GPHRS4mm9NaVKL8BZqUH@postgresql-hl.middleware:5432/safeline-ce
        - name: MANAGEMENT_LOGS_DIR
          value: /logs/management
        - name: TZ
          value: Asia/Shanghai
        # securityContext:
        #   capabilities:
        #     add: ["net_raw"]
        ports:
        - name: web-service
          containerPort: 1443
          protocol: TCP
        - name: middle-service
          containerPort: 1080
          protocol: TCP
        - name: controller-port
          containerPort: 9002
          protocol: TCP
        resources:
          limits:
            cpu: 1000m
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30


---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: safeline-mgt-api
    component: secure
  name: safeline-mgt-api
  namespace: waf
spec:
  ports:
  - name: web-svc
    port: 1443
    protocol: TCP
    targetPort: 1443
  - name: controller-svc
    port: 9002
    protocol: TCP
    targetPort: 9002
  selector:
    app: safeline-mgt-api
    component: secure
  type: NodePort
```

- safeline-detector.yaml
```yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: safeline-detector-data
  namespace: waf
spec:
  storageClassName: nfs-based-cstor-storage
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: safeline-detector-logs
  namespace: waf
spec:
  storageClassName: nfs-based-cstor-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: safeline-detector
    component: secure
  name: safeline-detector
  namespace: waf
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: safeline-detector
      component: secure
  template:
    metadata:
      labels:
        app: safeline-detector
        component: secure
    spec:
      imagePullSecrets:
      - name: harborsecret
      volumes:
      - name: safeline-detector-data
        persistentVolumeClaim:
          claimName: safeline-detector-data
      - name: safeline-detector-logs
        persistentVolumeClaim:
          claimName: safeline-detector-logs
      containers:
      - name: safeline-detector
        # image: 192.168.30.19/chaitin/safeline-detector:2.0.0
        image: chaitin/safeline-detector:2.0.1
        volumeMounts:
        - name: safeline-detector-data
          mountPath: /resources/detector
        - name: safeline-detector-logs
          mountPath: /logs/detector
        imagePullPolicy: Always
        env:
        - name: LOG_DIR
          value: /logs/detector
        - name: TZ
          value: Asia/Shanghai
        # securityContext:
        #   capabilities:
        #     add: ["net_raw"]
        ports:
        - name: svc-port
          containerPort: 8000
          protocol: TCP
        - name: health-port
          containerPort: 8001
          protocol: TCP

        resources:
          limits:
            cpu: 1000m
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: safeline-detector
    component: secure
  name: safeline-detector
  namespace: waf
spec:
  ports:
  - name: svc-port
    port: 8000
    protocol: TCP
    targetPort: 8000
  - name: health-port
    port: 8001
    protocol: TCP
    targetPort: 8001
  selector:
    app: safeline-detector
    component: secure
  type: ClusterIP
```

- safeline-mario.yaml
```yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: safeline-mario-data
  namespace: waf
spec:
  storageClassName: nfs-based-cstor-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: safeline-mario-logs
  namespace: waf
spec:
  storageClassName: nfs-based-cstor-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: safeline-mario
    component: secure
  name: safeline-mario
  namespace: waf
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: safeline-mario
      component: secure
  template:
    metadata:
      labels:
        app: safeline-mario
        component: secure
    spec:
      imagePullSecrets:
      - name: harborsecret
      volumes:
      - name: safeline-mario-data
        persistentVolumeClaim:
          claimName: safeline-mario-data
      - name: safeline-mario-logs
        persistentVolumeClaim:
          claimName: safeline-mario-logs
      #initContainers:
      #  - name: change-owner
      #    image: 192.168.30.19/library/busybox:1.36.1
      #    volumeMounts:
      #    - name: safeline-mario-data
      #      mountPath: /resources/mario
      #    - name: safeline-mario-logs
      #      mountPath: /logs/mario
      #    command: ['sh', '-c', 'chown 205:205 /resources/detector && chown 205:205 /logs/detector']
      containers:
      - name: safeline-mario
        # image: 192.168.30.19/chaitin/safeline-mario:2.0.0
        image: chaitin/safeline-mario:2.0.1
        volumeMounts:
        - name: safeline-mario-data
          mountPath: /resources/mario
        - name: safeline-mario-logs
          mountPath: /logs/mario
        imagePullPolicy: Always
        env:
        - name: LOG_DIR
          value: /logs/mario
        - name: TZ
          value: Asia/Shanghai
        - name: GOGC
          value: "100"
        - name: DATABASE_URL
          value: postgres://safeline-ce:GPHRS4mm9NaVKL8BZqUH@postgresql-hl.middleware:5432/safeline-ce
        - name: REDIS_URL
          value: redis://:E7qLW84bKomVLakotMNp@redis-master.middleware:6379/12
        # securityContext:
        #   #runAsUser: 205
        #   #runAsGroup: 205
        #   capabilities:
        #     add: ["net_raw"]

        ports:
        - containerPort: 3335
          protocol: TCP
        resources:
          limits:
            cpu: 1000m
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: safeline-mario
    component: secure
  name: safeline-mario
  namespace: waf
spec:
  ports:
  - name: safeline-mario
    port: 3335
    protocol: TCP
    targetPort: 3335
  selector:
    app: safeline-mario
    component: secure
  type: ClusterIP
```

- safeline-tengine.yaml
```yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: safeline-tengine-logs
  namespace: waf
spec:
  storageClassName: nfs-based-cstor-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: safeline-tengine-cache
  namespace: waf
spec:
  storageClassName: nfs-based-cstor-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: safeline-tengine
    component: secure
  name: safeline-tengine
  namespace: waf
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: safeline-tengine
      component: secure
  template:
    metadata:
      labels:
        app: safeline-tengine
        component: secure
    spec:
      imagePullSecrets:
      - name: harborsecret
      volumes:
      - name: mgr-api-nginx-conf
        persistentVolumeClaim:
          claimName: mgr-api-nginx-conf
      - name: mgr-api-certs
        persistentVolumeClaim:
          claimName: mgr-api-certs
      - name: safeline-detector-data
        persistentVolumeClaim:
          claimName: safeline-detector-data
      - name: safeline-tengine-logs
        persistentVolumeClaim:
          claimName: safeline-tengine-logs
      - name: safeline-tengine-cache
        persistentVolumeClaim:
          claimName: safeline-tengine-cache
      #initContainers:
      #  - name: change-owner
      #    image: 192.168.30.19/library/busybox:1.36.1
      #    volumeMounts:
      #    - name: safeline-tengine-data
      #      mountPath: /resources/mario
      #    - name: safeline-tengine-logs
      #      mountPath: /logs/mario
      #    command: ['sh', '-c', 'chown 205:205 /resources/detector && chown 205:205 /logs/detector']
      hostNetwork: true
      containers:
      - name: safeline-tengine
        # image: 192.168.30.19/chaitin/safeline-tengine:2.0.0
        image: chaitin/safeline-tengine:2.0.1
        volumeMounts:
        - name: mgr-api-nginx-conf
          mountPath: /etc/nginx
        - name: mgr-api-certs
          mountPath: /resources/management
        - name: safeline-detector-data
          mountPath: /resources/detector
        - name: safeline-tengine-logs
          mountPath: /var/log/nginx
        - name: safeline-tengine-cache
          mountPath: /usr/local/nginx/cache
        imagePullPolicy: Always
        env:
        - name: MGT_ADDR
          value: safeline-mgt-api:9002
        - name: TZ
          value: Asia/Shanghai
        #- name: GOGC
        #  value: "100"
        #- name: DATABASE_URL
        #  value: postgres://safeline-ce:GPHRS4mm9NaVKL8BZqUH@postgresql-hl.middleware:5432/safeline-ce
        #- name: REDIS_URL
        #  value: redis://:E7qLW84bKomVLakotMNp@redis-master.middleware:6379/12
        #securityContext:
        #  #runAsUser: 205
        #  #runAsGroup: 205
        #  capabilities:
        #    add: ["net_raw"]

        ports:
        - name: health-port
          containerPort: 65443
          protocol: TCP
        resources:
          limits:
            cpu: 1000m
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: safeline-tengine
    component: secure
  name: safeline-tengine
  namespace: waf
spec:
  ports:
  - name: safeline-tengine
    port: 65443
    protocol: TCP
    targetPort: 65443
  selector:
    app: safeline-tengine
    component: secure
  type: ClusterIP
```

**Comment by pusidun** [comment]
@charnet1019 师傅我之前也尝试过k8s部署，但是我看到一个配置
`bind_addr: unix:///resources/detector/snserver.sock` 用的是unix sock不是ip端口，k8s这个不好整吧？
另外`建议完善下官方文档，说明下每个服务的监听端口、作用及其服务调用关系` +1,比如那个mario不知道是干啥的，有次一个容器没起来我发现雷池也在正常拦截。
2.0提供了嵌入式版本，建议补充在那里

**Comment by charnet1019** [comment]
socket可以让两个pod挂载同一个pvc就可以了发自我的手机-------- 原始邮件 --------发件人： pusidun ***@***.***>日期： 2023年7月4日周二 17:54收件人： chaitin/safeline ***@***.***>抄送： charnet1019 ***@***.***>, Mention ***@***.***>主    题： Re: [chaitin/safeline] 是否可以部署到k8s？ (Issue #118)
@charnet1019 师傅我之前也尝试过k8s部署，但是我看到一个配置
bind_addr: unix:///resources/detector/snserver.sock 用的是unix sock不是ip端口，k8s这个不好整吧？
另外建议完善下官方文档，说明下每个服务的监听端口、作用及其服务调用关系 +1,比如那个mario不知道是干啥的，有次一个容器没起来我发现雷池也在正常拦截。
2.0提供了嵌入式版本，建议补充在那里

**Comment by charnet1019** [comment]
> @charnet1019 师傅我之前也尝试过k8s部署，但是我看到一个配置 `bind_addr: unix:///resources/detector/snserver.sock` 用的是unix sock不是ip端口，k8s这个不好整吧？ 另外`建议完善下官方文档，说明下每个服务的监听端口、作用及其服务调用关系` +1,比如那个mario不知道是干啥的，有次一个容器没起来我发现雷池也在正常拦截。 2.0提供了嵌入式版本，建议补充在那里

我又看了下，应该是safeline-detector服务有两各监听模式，一种是unix doamin sock模式，另一种是网络socket模式，在配置文件snserver.yml是可以修改，此处因Dockerfile中没有处理修改配置的功能，如下:
```yaml
fusion_sofile: ./config/libfusion2.so
ip_location_db: ./GeoLite2-City.mmdb
#bind_addr: unix:///resources/detector/snserver.sock        # sock模式
bind_addr: 0.0.0.0      # 网络socket模式
listen_port: 8000        # 网络socket模式
health_check_addr: 0.0.0.0
health_check_port: 8001
mgt_server_addr: ""
log: file:///logs/detector/snserver.log
log_level: warning
# worker: 4
daemon: false
heartbeat_interval: 5000
max_queue_size: 16384
rlimit_nofile: 65536
web_log_interval: 400
web_log: http://safeline-mario:3335/log/envelop
```

在safeline-tengine中可以验证此问题，因在/etc/nginx中有safeline.conf是用的网络socket模式调用safeline-detector；另一个safeline_nuix.conf中则是使用的sock模式调用的safeline-detector服务

**safeline.conf:**
```
upstream detector_server {
    keepalive   256;
    server      safeline-detector:8000;
    check       interval=5000 rise=1 fall=3 port=8001 type=http;
}
```

**safeline_unix.conf:**
```
upstream detector_server {
    keepalive   256;
    server      unix:/resources/detector/snserver.sock;
}
```

比较奇怪的是有请求qps数据展示，但没有请求数据及用户访问情况统计
![image](https://github.com/chaitin/safeline/assets/18616254/74dab435-cdea-4698-87a6-3f9a86d7df25)
