### ISSUE TITLE
[Bug] 当我启用Clash的TUN模式时无法访问面板

### ISSUE THREAD

**Issue by L1bws** [chaitin/SafeLine#1187]
### What happened?

我在打开了Clash（Meta内核）的TUN模式后无法访问雷池的面板，但是关闭TUN之后又正常了

### How we reproduce?

1.雷池正常运行，面板可正常访问
2.通过修改Clash的config.yaml启用TUN模式
3.再次访问雷池面板

### Expected behavior

正常渲染页面，且页面可以正常交互

### Error log

使用curl访问时：`curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to xxx.xxx.xxx.xxx`
浏览器访问：`ERR_CONNECTION_CLOSED`
其它：（Docker容器日志没有任何相关信息）

**Comment by L1bws** [comment]
这是有关TUN的配置：
```yaml
tun:
  auto-detect-interface: true
  auto-route: true
  device: Mihomo
  dns-hijack:
    - any:53
  mtu: 1500
  stack: gvisor
  strict-route: true
  enable: true
```
我还打开了DNS解析和SNI嗅探
