### ISSUE TITLE
Admin WebUI through traefik

### ISSUE THREAD

**Issue by lordraiden** [chaitin/SafeLine#1204]
### Content

I'm trying to proxy admin access with traefik, I have added labels this to mgt container.

```
  mgt:
    container_name: ${safeline_mgt_name}
    restart: always
    image: ${IMAGE_PREFIX}/safeline-mgt${REGION}${ARCH_SUFFIX}${RELEASE}:${IMAGE_TAG:?image tag required}
    <<: [*config, *dns]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${SAFELINE_DIR}/resources/mgt:/app/data
      - ${SAFELINE_DIR}/logs/nginx:/app/log/nginx:z
      - ${SAFELINE_DIR}/resources/sock:/app/sock
      - /var/run:/app/run
    ports:
      - ${MGT_PORT:-9443}:1443
    healthcheck:
      test: curl -k -f https://localhost:1443/api/open/health
    environment:
      - MGT_PG=postgres://safeline-ce:${POSTGRES_PASSWORD}@${safeline_postgres_name}/safeline-ce?sslmode=disable
    depends_on:
      - postgres
      - fvm
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    networks:
      eth2:
        ipv4_address: ${mgt_ip} #4 mgt
    labels:
      traefik.enable: true
      traefik.docker.network: eth2
      traefik.http.routers.mgt.entrypoints: https443
      traefik.http.routers.mgt.service: mgt
      traefik.http.routers.mgt.rule: "Host(`${safeline_mgt_name}.${mydomain}`)"
      traefik.http.routers.mgt.tls: true
      traefik.http.routers.mgt.middlewares: local-ipwhitelist@file, rate-limit@file
      traefik.http.services.mgt.loadbalancer.server.port: 1443

```

In traefik look fine like any other service I have

![Image](https://github.com/user-attachments/assets/b509c2ac-b6b9-4cbf-85a5-4df0aed7a949)

But when I try to access I can't reach it

![Image](https://github.com/user-attachments/assets/9c2f97bb-6d77-44c6-aca1-f10d11418df8)

via IP I have no problem.

![Image](https://github.com/user-attachments/assets/e1fa4142-9e19-4461-ad47-2c97cc7ccd43)

It's an internal proxy it's not published to internet
